# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Thinkpad/Documents/GitHub/OpenMIPS/OpenMIPS.srcs/sources_1/ip/rom0/rom0.xci
# IP: The module: 'rom0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Thinkpad/Documents/GitHub/OpenMIPS/OpenMIPS.srcs/sources_1/ip/rom0/rom0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Thinkpad/Documents/GitHub/OpenMIPS/OpenMIPS.srcs/sources_1/ip/rom0/rom0.xci
# IP: The module: 'rom0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Thinkpad/Documents/GitHub/OpenMIPS/OpenMIPS.srcs/sources_1/ip/rom0/rom0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
