# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/codehub/OpenMIPS_final/OpenMIPS.cache/wt [current_project]
set_property parent.project_path E:/codehub/OpenMIPS_final/OpenMIPS.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/codehub/OpenMIPS_final/OpenMIPS.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/codehub/OpenMIPS_final/OS.coe
add_files E:/codehub/OpenMIPS_final/ascii_zk.coe
add_files E:/codehub/OpenMIPS_final/GraphicRAM.coe
add_files E:/codehub/OpenMIPS_final/GPIOImage.coe
add_files E:/codehub/OpenMIPS_final/ROM/NewSOImage.coe
add_files e:/codehub/OpenMIPS_final/ROM/keyboard.bin.coe
read_verilog E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/OpenMIPS/OpenMIPS.vh
read_verilog -library xil_defaultlib {
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/ddr/DDR2.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/GraphicsController.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/OpenMIPS/LLbit_reg.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/OpenMIPS/cp0_reg.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/OpenMIPS/ctrl.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/OpenMIPS/div.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/OpenMIPS/ex.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/OpenMIPS/ex_mem.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/flash_rom.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/gpio/timescale.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/gpio/gpio_defines.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/gpio/gpio_top.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/OpenMIPS/hilo_reg.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/OpenMIPS/id.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/OpenMIPS/id_ex.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/OpenMIPS/if_id.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/keyboard.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/OpenMIPS/mem.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/OpenMIPS/mem_wb.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/OpenMIPS/openmips.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/OpenMIPS/pc_reg.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/phy_bus_addr_conv.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/uart/raminfr.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/OpenMIPS/regfile.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/seg8.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/OpenMIPS/tlb.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/uart/timescale.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/uart/uart_defines.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/uart/uart_debug_if.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/uart/uart_receiver.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/uart/uart_regs.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/uart/uart_rfifo.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/uart/uart_sync_flops.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/uart/uart_tfifo.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/uart/uart_top.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/uart/uart_transmitter.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/uart/uart_wb.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/vga1024x768.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/wb_conmax/wb_conmax_defines.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/wb_conmax/wb_conmax_arb.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/wb_conmax/wb_conmax_master_if.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/wb_conmax/wb_conmax_msel.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/wb_conmax/wb_conmax_pri_dec.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/wb_conmax/wb_conmax_pri_enc.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/wb_conmax/wb_conmax_rf.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/wb_conmax/wb_conmax_slave_if.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/wb_conmax/wb_conmax_top.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/OpenMIPS/wishbone_bus_if.v
  E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/openmips_min_sopc.v
}
read_vhdl -library xil_defaultlib E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/new/ddr/Ram2Ddr.vhd
read_ip -quiet E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all e:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc]

read_ip -quiet E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/ip/rom0/rom0.xci
set_property used_in_implementation false [get_files -all e:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/ip/rom0/rom0_ooc.xdc]

read_ip -quiet E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property used_in_implementation false [get_files -all e:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc]
set_property used_in_implementation false [get_files -all e:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc]

read_ip -quiet E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet E:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all e:/codehub/OpenMIPS_final/OpenMIPS.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/codehub/OpenMIPS_final/OpenMIPS.srcs/constrs_1/new/nexys4ddr.xdc
set_property used_in_implementation false [get_files E:/codehub/OpenMIPS_final/OpenMIPS.srcs/constrs_1/new/nexys4ddr.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental E:/codehub/OpenMIPS_final/OpenMIPS.srcs/utils_1/imports/synth_1/openmips_min_sopc.dcp
close [open __synthesis_is_running__ w]

synth_design -top openmips_min_sopc -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef -incremental_synth openmips_min_sopc.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file openmips_min_sopc_utilization_synth.rpt -pb openmips_min_sopc_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
